import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Nav from '@/components/nav'
import Topbar from '@/components/topbar'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
   <>
   <Head>
    <title>Digital App</title>
    <meta name="description" content='Generated by create next app'></meta>
    <meta name="viewport" content='width=device-width,initial-scale=1'></meta>
    <link rel='icon' href='/favicon.ico' />
   </Head>
   <Topbar />
   <Nav />

   
   </>
		
  )
}
